### ISSUE TITLE
Label bug and type error

### ISSUE THREAD

**Issue by MJinH** [apache/age-viewer#71] opened 2022-11-27 18:29 UTC
**Describe the bug**

#### I used the example query in apache age document and ag cloud
 (https://age.apache.org/age-manual/master/clauses/create.html)
(https://bitnine.net/ag-cloud/)

#### If I run a query that creates a new node with some properties after creating a new graph, the property name is listed correctly in node label.

![Screenshot (63)](https://user-images.githubusercontent.com/97130553/204151003-10c0689f-95f4-4a4d-baba-1f0873e68877.png)

#### but after that, if I run a query that creates a edge between two nodes, all the property names are suddenly moved to edge label.

![Screenshot (66)](https://user-images.githubusercontent.com/97130553/204151074-9a813fd1-898d-413b-b90b-7cf86f21bf3b.png)

#### when a query creates node and edge at the same time and input data is pretty large, then it works fine. Additionally, sometimes the following error is shown when running a query that creates a new node or edge even though the cypher query command has no error and works fine.

![Screenshot (65)](https://user-images.githubusercontent.com/97130553/204152639-1ba52c23-d02b-4e3e-868e-6ab31015aa1e.png)

 
**Desktop (please complete the following information):**
 - OS: window 10 pro
 - Browser chrome

**Additional context**

**Comment by marodins** [comment] 2022-11-28 20:24
I also noticed this issue. There are two issues here. It seems that one may be directly related to the backend and may possibly be related to the AGE extension. Specifically, I noticed that the query used to create nodes and two edge results in a node (center node that connects with two other nodes) is being recognized as an edge even though the query clearly created a node.

**Comment by marodins** [comment] 2022-11-29 01:33
Hi @MJinH ,

This issue is caused by a bug with the old query and parsing results from that query. I am currently working on a fix for this issue. @JoshInnis and I worked on creating a new query. I will implement it and fix web app code as necessary.

**Closed** 2022-12-16 22:37 UTC
Labels: bug
