### ISSUE TITLE
Label (oid) cache corrupted

### ISSUE THREAD

**Issue by MJinH** [apache/age-viewer#83] opened 2022-12-16 21:44 UTC
**Describe the bug**
This bug happens when refreshing the browser several times.

**Screenshots**
![Screenshot (87)](https://user-images.githubusercontent.com/97130553/208193673-310587e8-a0ea-45f6-930a-867c0b1f9ffb.png)

**Desktop (please complete the following information):**
 - OS: window 10 pro
 - Browser chrome

**Comment by marodins** [comment] 2022-12-19 16:25
I believe this is caused by the old meta data retrieval query. PR https://github.com/apache/age-viewer/pull/75 still needs to be merged, and should fix this.

**Comment by MJinH** [comment] 2022-12-29 21:24
#75 is merged.

**Closed** 2022-12-29 21:23 UTC
Labels: bug
